// generated by stringer -type=SSE2Instr codegen/sse2; DO NOT EDIT

package sse2

import "fmt"

const _SSE2Instr_name = "INVALIDLoadSi128LoaduSi128StoreuSi128AddEpi64SubEpi64MulEpu32ShufflehiEpi16ShuffleloEpi16ShuffleEpi32SlliSi128SrliSi128UnpackhiEpi64UnpackloEpi64AddPdAddSdAndnotPdCmpeqPdCmpeqSd"

var _SSE2Instr_index = [...]uint8{0, 7, 16, 26, 37, 45, 53, 61, 75, 89, 101, 110, 119, 132, 145, 150, 155, 163, 170, 177}

func (i SSE2Instr) String() string {
	if i < 0 || i >= SSE2Instr(len(_SSE2Instr_index)-1) {
		return fmt.Sprintf("SSE2Instr(%d)", i)
	}
	return _SSE2Instr_name[_SSE2Instr_index[i]:_SSE2Instr_index[i+1]]
}
