// generated by stringer -type=SSE2Instr codegen/sse2; DO NOT EDIT

package sse2

import "fmt"

const _SSE2Instr_name = "INVALIDMOVDQAMOVDQUPADDQPSUBQPMULUDQPSHUFHWPSHUFLWPSHUFDPSLLDQPSRLDQPUNPCKHQDQPUNPCKLQDQADDPDADDSDANDNPDCMPPDCMPSD"

var _SSE2Instr_index = [...]uint8{0, 7, 13, 19, 24, 29, 36, 43, 50, 56, 62, 68, 78, 88, 93, 98, 104, 109, 114}

func (i SSE2Instr) String() string {
	if i < 0 || i >= SSE2Instr(len(_SSE2Instr_index)-1) {
		return fmt.Sprintf("SSE2Instr(%d)", i)
	}
	return _SSE2Instr_name[_SSE2Instr_index[i]:_SSE2Instr_index[i+1]]
}
